### ISSUE TITLE
Assets can not delete

### ISSUE THREAD

**Issue by Sceko** [statamic/statamic#6] opened 2020-01-23 10:01 UTC
After create in assets Contalner can not delete him only edit add functions for delete
![Screenshot 2020-01-23 at 11 01 54](https://user-images.githubusercontent.com/2323952/72974712-c6241700-3dcf-11ea-963a-647fb8a88273.png)

**Comment by jackmcdade** [comment] 2020-01-23 14:23
Thank you for the report! This is actually a duplicate of [statamic/cms#836](https://github.com/statamic/cms/issues/836) so I'l be closing this one.

**Closed by jackmcdade** 2020-01-23 14:23 UTC
